
package ir.navaco.mcb.sms.gateway.consumer.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaskanSendService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://212.1.193.164/MaskanSMSService.asmx?WSDL")
public class MaskanSendService
    extends Service
{

    private final static URL MASKANSENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException MASKANSENDSERVICE_EXCEPTION;
    private final static QName MASKANSENDSERVICE_QNAME = new QName("http://tempuri.org/", "MaskanSendService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://212.1.193.164/MaskanSMSService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MASKANSENDSERVICE_WSDL_LOCATION = url;
        MASKANSENDSERVICE_EXCEPTION = e;
    }

    public MaskanSendService() {
        super(__getWsdlLocation(), MASKANSENDSERVICE_QNAME);
    }

    public MaskanSendService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MASKANSENDSERVICE_QNAME, features);
    }

    public MaskanSendService(URL wsdlLocation) {
        super(wsdlLocation, MASKANSENDSERVICE_QNAME);
    }

    public MaskanSendService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MASKANSENDSERVICE_QNAME, features);
    }

    public MaskanSendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaskanSendService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaskanSendServiceSoap
     */
    @WebEndpoint(name = "MaskanSendServiceSoap")
    public MaskanSendServiceSoap getMaskanSendServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSendServiceSoap"), MaskanSendServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaskanSendServiceSoap
     */
    @WebEndpoint(name = "MaskanSendServiceSoap")
    public MaskanSendServiceSoap getMaskanSendServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSendServiceSoap"), MaskanSendServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MaskanSendServiceSoap
     */
    @WebEndpoint(name = "MaskanSendServiceSoap12")
    public MaskanSendServiceSoap getMaskanSendServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSendServiceSoap12"), MaskanSendServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaskanSendServiceSoap
     */
    @WebEndpoint(name = "MaskanSendServiceSoap12")
    public MaskanSendServiceSoap getMaskanSendServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSendServiceSoap12"), MaskanSendServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MASKANSENDSERVICE_EXCEPTION!= null) {
            throw MASKANSENDSERVICE_EXCEPTION;
        }
        return MASKANSENDSERVICE_WSDL_LOCATION;
    }

}
