
package ir.navaco.mcb.sms.gateway.consumer.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaskanSMSService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.30.1.65:8080/maskansmsservice.asmx?WSDL")
public class MaskanSMSService
    extends Service
{

    private final static URL MASKANSMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MASKANSMSSERVICE_EXCEPTION;
    private final static QName MASKANSMSSERVICE_QNAME = new QName("http://tempuri.org/", "MaskanSMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.30.1.65:8080/maskansmsservice.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MASKANSMSSERVICE_WSDL_LOCATION = url;
        MASKANSMSSERVICE_EXCEPTION = e;
    }

    public MaskanSMSService() {
        super(__getWsdlLocation(), MASKANSMSSERVICE_QNAME);
    }

    public MaskanSMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MASKANSMSSERVICE_QNAME, features);
    }

    public MaskanSMSService(URL wsdlLocation) {
        super(wsdlLocation, MASKANSMSSERVICE_QNAME);
    }

    public MaskanSMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MASKANSMSSERVICE_QNAME, features);
    }

    public MaskanSMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaskanSMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaskanSMSServiceSoap
     */
    @WebEndpoint(name = "MaskanSMSServiceSoap")
    public MaskanSMSServiceSoap getMaskanSMSServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSMSServiceSoap"), MaskanSMSServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaskanSMSServiceSoap
     */
    @WebEndpoint(name = "MaskanSMSServiceSoap")
    public MaskanSMSServiceSoap getMaskanSMSServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSMSServiceSoap"), MaskanSMSServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MaskanSMSServiceSoap
     */
    @WebEndpoint(name = "MaskanSMSServiceSoap12")
    public MaskanSMSServiceSoap getMaskanSMSServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSMSServiceSoap12"), MaskanSMSServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaskanSMSServiceSoap
     */
    @WebEndpoint(name = "MaskanSMSServiceSoap12")
    public MaskanSMSServiceSoap getMaskanSMSServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MaskanSMSServiceSoap12"), MaskanSMSServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MASKANSMSSERVICE_EXCEPTION!= null) {
            throw MASKANSMSSERVICE_EXCEPTION;
        }
        return MASKANSMSSERVICE_WSDL_LOCATION;
    }

}
